import { Check, ChevronLeft, ChevronRight, Plus, Search, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { addGarments, createOrder, listClients, listGarmentTypes } from '../api/orders'
import { errorMessage } from '../api/client'
import type { Cliente, PrendaDraft, TipoPrenda } from '../types'

const blankGarment = (): PrendaDraft => ({ tipo_prenda_id: '', cantidad: 1, color: '', descripcion: '' })
const steps = ['Cliente', 'Prendas', 'Resumen']
export function NewOrderPage() {
  const [step, setStep] = useState(1); const [clients, setClients] = useState<Cliente[]>([]); const [types, setTypes] = useState<TipoPrenda[]>([])
  const [selected, setSelected] = useState<Cliente | null>(null); const [search, setSearch] = useState(''); const [garments, setGarments] = useState<PrendaDraft[]>([blankGarment()])
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [createdId, setCreatedId] = useState<number | null>(null)
  useEffect(() => { Promise.all([listClients(), listGarmentTypes()]).then(([c,t]) => { setClients(c.filter(x => x.activo)); setTypes(t.filter(x => x.activo)) }).catch(e => setError(errorMessage(e))).finally(() => setLoading(false)) }, [])
  const filtered = useMemo(() => { const value = search.toLowerCase().trim(); return value ? clients.filter(c => `${c.nombre} ${c.apellido} ${c.telefono} ${c.email ?? ''}`.toLowerCase().includes(value)) : clients }, [clients, search])
  function updateGarment(index: number, patch: Partial<PrendaDraft>) { setGarments(current => current.map((item, i) => i === index ? { ...item, ...patch } : item)) }
  function next() { setError(''); if (step === 1 && !selected) return setError('Selecciona un cliente para continuar.'); if (step === 2 && garments.some(g => !g.tipo_prenda_id || !Number.isInteger(g.cantidad) || g.cantidad <= 0)) return setError('Selecciona el tipo y una cantidad mayor que cero para cada prenda.'); setStep(s => Math.min(s + 1, 3)) }
  async function submit() { if (!selected) return; setSubmitting(true); setError(''); try { const order = await createOrder(selected.id); await addGarments(order.id, garments); setCreatedId(order.id) } catch (e) { setError(errorMessage(e)) } finally { setSubmitting(false) } }
  if (createdId) return <section className="order-success"><span><Check size={48}/></span><h1>Pedido creado correctamente</h1><p>Número de pedido</p><strong>#SLV-{String(createdId).padStart(4,'0')}</strong><button className="primary" onClick={() => { setCreatedId(null); setStep(1); setSelected(null); setGarments([blankGarment()]) }}>Crear otro pedido</button></section>
  return <section className="order-page"><div className="stepper">{steps.map((label, index) => { const number = index + 1; return <div className={`step ${step === number ? 'current' : ''} ${step > number ? 'done' : ''}`} key={label}><span>{step > number ? <Check size={19}/> : number}</span><small>{label}</small></div> })}</div>
    <section className="wizard-card">
      {step === 1 && <><h1>Seleccionar cliente</h1><p>Busca un cliente existente para asociarlo al pedido.</p><label className="search"><Search size={20}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por nombre, teléfono o correo…"/></label><div className="client-list">{loading ? <div className="state"><span className="spinner"/>Cargando clientes…</div> : filtered.length ? filtered.map(c => <button key={c.id} className={selected?.id === c.id ? 'selected' : ''} onClick={() => setSelected(c)}><span className="avatar">{c.nombre[0]}{c.apellido[0]}</span><span><b>{c.nombre} {c.apellido}</b><small>{c.telefono}{c.email ? ` · ${c.email}` : ''}</small></span>{selected?.id === c.id && <Check/>}</button>) : <div className="state">No se encontraron clientes.</div>}</div></>}
      {step === 2 && <><h1>Agregar prendas</h1><p>Detalla las prendas que trae el cliente.</p>{garments.map((garment, index) => <section className="garment" key={index}><header><b>Prenda {index + 1}</b>{garments.length > 1 && <button className="danger-link" onClick={() => setGarments(g => g.filter((_,i) => i !== index))}><Trash2 size={17}/>Eliminar</button>}</header><div className="form-grid"><label>Tipo de prenda *<select value={garment.tipo_prenda_id} onChange={e => updateGarment(index, { tipo_prenda_id: Number(e.target.value) || '' })}><option value="">Seleccionar tipo</option>{types.map(t => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><label>Cantidad *<input type="number" min="1" step="1" value={garment.cantidad} onChange={e => updateGarment(index, { cantidad: Number(e.target.value) })}/></label><label>Color<input value={garment.color} maxLength={50} onChange={e => updateGarment(index, { color: e.target.value })} placeholder="Blanco, azul…"/></label><label>Observaciones<input value={garment.descripcion} maxLength={255} onChange={e => updateGarment(index, { descripcion: e.target.value })} placeholder="Manchas, instrucciones…"/></label></div></section>)}<button className="add-link" onClick={() => setGarments(g => [...g, blankGarment()])}><Plus size={18}/>Agregar otra prenda</button></>}
      {step === 3 && <><h1>Resumen del pedido</h1><p>Revisa los detalles antes de crear el pedido.</p><div className="summary-client"><small>Cliente</small><b>{selected?.nombre} {selected?.apellido}</b><span>{selected?.telefono}</span></div>{garments.map((g,i) => <div className="summary-garment" key={i}><span><b>{types.find(t => t.id === g.tipo_prenda_id)?.nombre} × {g.cantidad}</b><small>{[g.color,g.descripcion].filter(Boolean).join(' · ') || 'Sin observaciones'}</small></span></div>)}</>}
      {error && <div className="alert error">{error}</div>}<footer>{step > 1 ? <button className="secondary" onClick={() => { setError(''); setStep(s => s - 1) }}><ChevronLeft size={18}/>Anterior</button> : <span/>}{step < 3 ? <button className="primary" onClick={next}>Siguiente<ChevronRight size={18}/></button> : <button className="primary" onClick={() => void submit()} disabled={submitting}><Check size={18}/>{submitting ? 'Creando…' : 'Crear pedido'}</button>}</footer>
    </section></section>
}
